### ISSUE TITLE
content of bibl popups

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#48] opened 2019-10-15 18:52 UTC
We spent some time last meeting looking at the bibl popups on the P5 site and their content.

After discussion, we decided we'd rather have a brief identification of the work in the popup rather than a reflection of the full record in the bibliography.

Please look at the contents we used in the P4 bibl popups as a guide.

On that same model, we would also prefer not to color the contents of the bibl, even though it could help the reader identify clickable text.

(I'm about to mention a slightly different issue but it's tangential here: We recognized we need to talk more about rendering the authoritative bibliography to move it out of TEI Boilerplate and we have ideas about how to format it. Happily it uses a small number of elements.)

**Comment by mdalmau** [comment] 2019-10-24 19:30
Here's information, including XPaths, for the pop-up citations: https://iu.app.box.com/notes/545445019301.  We are working through some of the details with the team, but all agree that it's a good start.

**Comment by Conal-Tuohy** [comment] 2019-10-25 06:07
closing as duplicate of #21

**Closed by Conal-Tuohy** 2019-10-25 06:07 UTC
Labels: duplicate, rendering
