### ISSUE TITLE
Bibliography Font Rendition: blackletter font and red highlights

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#57] opened 2019-12-20 17:40 UTC
Creating a new issue based on the following email.  @wehooper could you add more context here so we know what this is about exactly:

> Hi Con and Michelle,
>  
> AT the meeting, we’ve just looked through the entries in the new authoritative bibliography, and we think it looks fine.
>  
> We can take over the problem of implementing the blackletter font and red highlights if not completed and any other developments of this component.
>  
> Wally and the team

**Comment by Conal-Tuohy** [comment] 2020-01-17 06:58
What is the issue with the blackletter font and red highlights?

**Comment by mdalmau** [comment] 2020-06-03 14:54
@wehooper could you review and clarify?  I am running through the open issues, tagging those that need future work accordingly, but I am not sure about this one.

**Comment by wehooper** [comment] 2020-08-17 21:28
The background issue is that title pages in some of Newton's source publications featured blackletter fonts or red-ink highlights, and we are now planning to reproduce those features if we can.

This is a new, post-NF idea, so we thought Takatomo could/should tackle the problem, presumably in the CSS3. We need to know how those bibl pop-ups work now.

**Comment by Conal-Tuohy** [comment] 2020-08-18 00:32
See https://github.com/IUBLibTech/newton_chymistry/blob/master/xslt/p5-to-html.xsl#L463-L502

**Comment by Conal-Tuohy** [comment] 2020-08-18 01:04
You might well ask "Why do you first stash this bibliographic data in an attribute and then later convert it to a popup? Why not just generate the popup (`details`) widget directly from the TEI?". This is an implementation detail not directly relevant to the issue at hand, but to avoid confusion, I will explain that the reason is because of how the Solr indexing is plugged into the system:

NB the Solr index is not generated directly from the TEI but from the HTML which was itself generated from the TEI. There is one set of TEI, but two flavours of HTML generated from it, and hence two Solr indices (diplomatic, and normalized). By generating the Solr index from the HTML, we can be sure that the "highlight" snippets which are returned from a Solr query must always match the HTML which is being displayed, and hence the highlights can be inserted back into the page that's displayed to the user. If the TEI-to-HTML stylesheet is ever modified, then the data in Solr will also reflect that modification.

What this means, though, is that snippets which are interpolated into the manuscript texts (like these bibliographic popups) need to be excluded from the index, otherwise it would be impossible to search for a phrase of Newton's which happened to include a bibliographic reference. So this is why I've stored them inside `title` attributes; the Solr index is only of the HTML text content, and doesn't include any attribute values.

**Comment by tubesoft** [comment] 2020-09-02 15:10
I modified and added on bibiography-to-html.xsl and tei.css. In my local environment, it worked. I committed the code on the branch, "[rendition_issues](https://github.com/IUBLibTech/newton_chymistry/tree/rendition_issues)".

**Comment by wehooper** [comment] 2021-02-15 21:11
This feature is working as it should. We can close this issue.

**Closed by wehooper** 2021-02-15 21:11 UTC
Labels: awaiting signoff, bibliography, rendering
